[shclustering]
conf_replication_include.alert_manager = true
conf_replication_include.alert_manager_alert_status = true
conf_replication_include.alert_manager_notification_schemes = true
conf_replication_include.alert_manager_email_templates = true
